GET http://localhost:8000/api/vehicle?vehicle=BN123s

###
GET http://localhost:8000/api/entry?entry=BN123d

###
GET http://localhost:8000/api/space

###
POST http://localhost:8000/api/entry
Content-Type: application/json

{
    "driver" : "Driver name",
    "space" : 1,
    "vehicle" : "BN123"
}

###
POST http://localhost:8000/api/exit?vehicle=BN123
